FROM python:3.10.9-slim

RUN python -m pip install rasa

WORKDIR /app
COPY . .

RUN rasa train nlu

# set the user to run dont run as root
USER 1001

# SET entry point for interactive shells
ENTRYPOINT [ "rasa" ]

CMD [ "run", "--enable-api", "--port","8080" ]