on:
  push:
    branches:
      - main
    paths:
    - 'actions/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build Action Server image and upgrade Rasa X/Enterprise deployment
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - id: action_server
      name: Build an action server with custom actions
      uses: RasaHQ/action-server-gha@main
      with:
        docker_image_name: 'account_username/repository_name'
        docker_registry_username: 'ehtesham9023'
        docker_registry_password: 'docker1101'
        docker_image_tag: ${{ github.sha }}
